[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  NODE_ENV = "development"

[build.environment]
  KEYFIRE = "AIzaSyDXQNAJtErwRQ8a7zQN38F85pY89fcWACI"
  KEYTRACER = "c3bb49f3c53549ce903f65141dbb9632@o473118"

  [build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true